# Generated by Django 5.2 on 2025-04-29 12:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0008_delete_customer'),
        ('khatabook', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='khatabook',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='khatabook_orders', to='items.order'),
        ),
    ]
