# Generated by Django 5.2 on 2025-04-29 12:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('khatabook', '0002_alter_khatabook_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='khatabook',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 4, 29, 17, 47, 9, 988443)),
            preserve_default=False,
        ),
    ]
