# Generated by Django 5.2 on 2025-05-13 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('khatabook', '0002_alter_khatabook_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='khatabook',
            name='customer_name',
            field=models.CharField(default='aditya', max_length=255),
            preserve_default=False,
        ),
    ]
