# Generated by Django 5.2 on 2025-05-08 14:47

import django.db.models.deletion
import users.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('notification_type', models.CharField(choices=[('stock', 'Stock Alert'), ('turnover', 'Monthly Turnover'), ('info', 'General Info'), ('greet', 'Greet'), ('update', 'Update')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read_by', models.ManyToManyField(blank=True, related_name='read_notifications', to=settings.AUTH_USER_MODEL)),
                ('shop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('report_id', models.CharField(default=users.models.uid, editable=False, max_length=255, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('Bug Report', 'Bug Report'), ('Feature Request', 'Feature Request'), ('General Suggestion', 'General Suggestion'), ('Complaint', 'Complaint'), ('Praise', 'Praise'), ('Other', 'Other')], max_length=50)),
                ('subject', models.CharField(blank=True, max_length=50, null=True)),
                ('report', models.TextField(blank=True, null=True)),
                ('is_solved', models.BooleanField(default=False)),
                ('report_at', models.DateTimeField(auto_now_add=True)),
                ('report_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
