# Generated by Django 5.2 on 2025-04-11 19:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('report_id', models.CharField(default='#REPO008aae474e', editable=False, max_length=255, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('Bug Report', 'Bug Report'), ('Feature Request', 'Feature Request'), ('General Suggestion', 'General Suggestion'), ('Complaint', 'Complaint'), ('Praise', 'Praise'), ('Other', 'Other')], max_length=50)),
                ('subject', models.CharField(blank=True, max_length=50, null=True)),
                ('report', models.TextField(blank=True, null=True)),
                ('report_at', models.DateTimeField(auto_now_add=True)),
                ('report_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
