# Generated by Django 5.2 on 2025-04-12 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='is_solved',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='report',
            name='report_id',
            field=models.CharField(default='#REPO00d2b99065', editable=False, max_length=255, primary_key=True, serialize=False),
        ),
    ]
