# Generated by Django 5.2 on 2025-05-17 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_notification_created_at_alter_report_report_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='task_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('stock', 'Stock Alert'), ('turnover', 'Monthly Turnover'), ('info', 'General Info'), ('finance', 'Finance Update'), ('greet', 'Greet'), ('update', 'Update')], max_length=20),
        ),
    ]
