# Generated by Django 5.2 on 2025-04-12 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_report_is_solved_alter_report_report_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='report_id',
            field=models.CharField(default='#REPO00fbd7c3c1', editable=False, max_length=255, primary_key=True, serialize=False),
        ),
    ]
