# Generated by Django 5.2 on 2025-04-12 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_report_report_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='report_id',
            field=models.CharField(default='#REPO00b832b3b2', editable=False, max_length=255, primary_key=True, serialize=False),
        ),
    ]
