# Generated by Django 5.2 on 2025-04-12 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_report_report_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='is_solved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='report',
            name='report_id',
            field=models.CharField(default='#REPO008d445217', editable=False, max_length=255, primary_key=True, serialize=False),
        ),
    ]
