# Generated by Django 5.2 on 2025-04-12 17:02

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_report_is_solved_alter_report_report_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='report_id',
            field=models.CharField(default=users.models.uid, editable=False, max_length=255, primary_key=True, serialize=False),
        ),
    ]
