# Generated by Django 5.2 on 2025-05-08 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='monthlyfinancesummary',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='monthlyfinancesummary',
            name='profit_margin',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
