# Generated by Django 5.2 on 2025-05-09 16:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_alter_monthlyfinancesummary_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyfinancesummary',
            name='recorded_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='monthlyfinancesummary',
            name='recorded_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
