# Generated by Django 5.2 on 2025-05-10 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_alter_dailyfinancesummary_recorded_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyfinancesummary',
            name='recorded_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
