# Generated by Django 5.2 on 2025-05-10 10:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_alter_dailyfinancesummary_recorded_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyfinancesummary',
            name='recorded_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
