# Generated by Django 5.2 on 2025-05-12 18:02

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_alter_dailyfinancesummary_recorded_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dailyfinancesummary',
            unique_together={('shop', 'recorded_at')},
        ),
    ]
