# Generated by Django 5.2 on 2025-05-12 18:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_alter_dailyfinancesummary_unique_together'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dailyfinancesummary',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='dailyfinancesummary',
            constraint=models.UniqueConstraint(fields=('shop', 'recorded_at'), name='unique_shop_recorded_at'),
        ),
    ]
