# Generated by Django 5.2 on 2025-05-08 14:47

import django.db.models.deletion
import django.utils.timezone
import items.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.CharField(default=items.models.uid, editable=False, max_length=255, primary_key=True, serialize=False)),
                ('customer', models.CharField(default='Guest', max_length=50)),
                ('customer_phone', models.CharField(blank=True, max_length=15, null=True)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('razorpay_order_id', models.CharField(blank=True, max_length=255, null=True)),
                ('razorpay_payment_id', models.CharField(blank=True, max_length=255, null=True)),
                ('razorpay_signature', models.CharField(blank=True, max_length=50, null=True)),
                ('is_paid', models.BooleanField(default=False)),
                ('payment_mode', models.CharField(max_length=50)),
                ('order_at', models.DateTimeField(auto_now_add=True)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_owner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255)),
                ('product_price', models.DecimalField(decimal_places=2, help_text='Sell Price', max_digits=10)),
                ('unit', models.CharField(choices=[('kg', 'Kilogram'), ('g', 'Gram'), ('l', 'Liter'), ('ml', 'Milliliter'), ('pcs', 'Pieces')], default='kg', max_length=10)),
                ('quantity', models.FloatField(default=1, verbose_name='quantity')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='items.order')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.CharField(default=items.models.uid, editable=False, max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, help_text='Sell Price', max_digits=15)),
                ('purchase_price', models.DecimalField(decimal_places=2, help_text='Purchase Price', max_digits=15)),
                ('stock', models.FloatField(default=1, verbose_name='total_stock')),
                ('stock_unit', models.CharField(choices=[('kg', 'Kilogram'), ('g', 'Gram'), ('l', 'Liter'), ('ml', 'Milliliter'), ('pcs', 'Pieces')], default='kg', max_length=10)),
                ('r_stock', models.FloatField(default=0, verbose_name='remaining_stock')),
                ('r_stock_unit', models.CharField(choices=[('kg', 'Kilogram'), ('g', 'Gram'), ('l', 'Liter'), ('ml', 'Milliliter'), ('pcs', 'Pieces')], default='kg', max_length=10, verbose_name='remaining_stock_unit')),
                ('images', models.ImageField(blank=True, null=True, upload_to='product_images/')),
                ('rack', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('category', models.CharField(choices=[('GROCERY', 'Grocery'), ('DAILY_ESSENTIALS', 'Daily Essentials'), ('SNACKS_AND_NAMKEEN', 'Snacks & Namkeen'), ('BEVERAGES', 'Beverages'), ('FRUITS_AND_VEGETABLES', 'Fruits & Vegetables'), ('OILS_AND_GHEE', 'Oils & Ghee'), ('SPICES', 'Spices'), ('PERSONAL_CARE', 'Personal Care'), ('HOME_CARE', 'Home Care'), ('BABY_CARE', 'Baby Care'), ('CLEANING_SUPPLIES', 'Cleaning Supplies'), ('STATIONERY', 'Stationery'), ('PLASTIC_PRODUCTS', 'Plastic Products'), ('FURNITURE', 'Furniture'), ('PET_CARE', 'Pet Care'), ('KITCHENWARE', 'Kitchenware'), ('COSMETICS', 'Cosmetics'), ('ELECTRONICS', 'Electronics'), ('TOYS', 'Toys'), ('OTHERS', 'Others')], default='OTHERS', max_length=50)),
                ('listed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='add_by_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
