# Generated by Django 5.2 on 2025-04-25 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='r_stock',
            field=models.CharField(blank=True, default=0, max_length=15, null=True, verbose_name='remaing_stock'),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.CharField(max_length=15, verbose_name='total_stock'),
        ),
    ]
