# Generated by Django 5.2 on 2025-04-25 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_product_r_stock_alter_product_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='unit',
            field=models.CharField(choices=[('g', 'Gram'), ('kg', 'Kilogram')], default='kg', max_length=10),
        ),
        migrations.AddField(
            model_name='product',
            name='r_stock_unit',
            field=models.CharField(choices=[('g', 'Gram'), ('kg', 'Kilogram')], default='kg', max_length=10),
        ),
        migrations.AddField(
            model_name='product',
            name='stock_unit',
            field=models.CharField(choices=[('g', 'Gram'), ('kg', 'Kilogram')], default='kg', max_length=10),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product_price',
            field=models.DecimalField(decimal_places=2, help_text='Sell Price', max_digits=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Sell Price', max_digits=15),
        ),
        migrations.AlterField(
            model_name='product',
            name='purchase_price',
            field=models.DecimalField(decimal_places=2, help_text='Purchase Price', max_digits=15),
        ),
        migrations.AlterField(
            model_name='product',
            name='r_stock',
            field=models.FloatField(default=0, verbose_name='remaing_stock'),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.FloatField(verbose_name='total_stock'),
        ),
    ]
