# Generated by Django 5.2 on 2025-04-25 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_orderitem_unit_product_r_stock_unit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='r_stock_unit',
            field=models.CharField(choices=[('g', 'Gram'), ('kg', 'Kilogram')], default='kg', max_length=10, verbose_name='remaing_stock_unit'),
        ),
    ]
