# Generated by Django 5.2 on 2025-04-25 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0004_alter_orderitem_subtotal_alter_product_r_stock_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('GROCERY', 'Grocery'), ('DAILY_ESSENTIALS', 'Daily Essentials'), ('SNACKS_AND_NAMKEEN', 'Snacks & Namkeen'), ('BEVERAGES', 'Beverages'), ('FRUITS_AND_VEGETABLES', 'Fruits & Vegetables'), ('OILS_AND_GHEE', 'Oils & Ghee'), ('SPICES', 'Spices'), ('PERSONAL_CARE', 'Personal Care'), ('HOME_CARE', 'Home Care'), ('BABY_CARE', 'Baby Care'), ('CLEANING_SUPPLIES', 'Cleaning Supplies'), ('STATIONERY', 'Stationery'), ('PLASTIC_PRODUCTS', 'Plastic Products'), ('FURNITURE', 'Furniture'), ('PET_CARE', 'Pet Care'), ('KITCHENWARE', 'Kitchenware'), ('COSMETICS', 'Cosmetics'), ('ELECTRONICS', 'Electronics'), ('TOYS', 'Toys'), ('OTHERS', 'Others')], default='OTHERS', max_length=50),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='unit',
            field=models.CharField(choices=[('kg', 'Kilogram'), ('g', 'Gram'), ('l', 'Liter'), ('ml', 'Milliliter'), ('pcs', 'Pieces')], default='kg', max_length=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='r_stock',
            field=models.FloatField(default=0, verbose_name='remaining_stock'),
        ),
        migrations.AlterField(
            model_name='product',
            name='r_stock_unit',
            field=models.CharField(choices=[('kg', 'Kilogram'), ('g', 'Gram'), ('l', 'Liter'), ('ml', 'Milliliter'), ('pcs', 'Pieces')], default='kg', max_length=10, verbose_name='remaining_stock_unit'),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock_unit',
            field=models.CharField(choices=[('kg', 'Kilogram'), ('g', 'Gram'), ('l', 'Liter'), ('ml', 'Milliliter'), ('pcs', 'Pieces')], default='kg', max_length=10),
        ),
    ]
