# Generated by Django 5.2 on 2025-04-25 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0005_product_category_alter_orderitem_unit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='rack',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.FloatField(default=1, verbose_name='total_stock'),
        ),
    ]
