# Generated by Django 5.2 on 2025-04-29 12:08

import items.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0006_alter_product_rack_alter_product_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_id',
            field=models.CharField(default=items.models.productid, editable=False, primary_key=True, serialize=False),
        ),
    ]
