# Generated by Django 5.2 on 2025-04-13 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0006_order_payment_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_mode',
            field=models.CharField(max_length=50),
        ),
    ]
