# Generated by Django 5.2 on 2025-04-29 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0007_alter_product_product_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
