# Generated by Django 5.2 on 2025-04-29 15:44

import django.db.models.deletion
import items.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0008_delete_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceModel',
            fields=[
                ('invoice_id', models.CharField(default=items.models.uid, editable=False, max_length=255, primary_key=True, serialize=False)),
                ('invoice_file', models.FileField(upload_to='invoices/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_invoice', to='items.order', verbose_name='order_invoice')),
            ],
        ),
    ]
