# Generated by Django 5.2 on 2025-04-30 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0010_invoicemodel_shop_alter_invoicemodel_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InvoiceModel',
        ),
    ]
