# Generated by Django 5.2 on 2025-05-10 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('phonebook', '0002_alter_addcontact_created_at'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='addcontact',
            unique_together=set(),
        ),
    ]
